# Generated by Django 5.0.6 on 2024-07-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plp_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
